import AuthProvider from '@/../components/AuthProvider/AuthProvider'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}> <AuthProvider>   {children} </AuthProvider> </body>
     
      <script src="https://cdn.tailwindcss.com"></script>
    </html>
  )
}
